# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
aliases:
  - &container_python
    docker:
      - image: cimg/python:3.9.10  # primary container for the build job

  - &run_task_install_tox_dependencies
    run:
      name: install tox dependencies
      command: |
        sudo apt-get -qq update
        sudo apt install -y build-essential libssl-dev libpython2-dev python3-pip
        sudo pip3 install tox
  - &run_task_install_dependencies_poetry
    run:
      name: Setup, install Poetry & dependencies
      command: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_UNINSTALL=1 python -
        curl -sSL https://install.python-poetry.org | python3 -
        poetry env use 3.9.10
        poetry install
  - &build_upload_to_pipy
    run:
      name: Create the distribution files & Upload to PyPI
      command: |
        # Relies on the PYPI_USERNAME and PYPI_PASSWORD environment variables configured at:
        #   https://circleci.com/gh/harmouch101/frozndict/edit#env-vars
        poetry publish --build --username "${PYPI_USERNAME}" --password "${PYPI_PASSWORD}" --no-interaction

jobs:
  testing:
    <<: *container_python
    steps:
      # Get the code
      - checkout
      # Cache
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - *run_task_install_tox_dependencies
      - *run_task_install_dependencies_poetry
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: run tests
          command: |
            tox -e test
      - store_test_results:
          path: .tox/test/tmp/reports

  build_deploy:
    <<: *container_python
    steps:
      # Get the code
      - checkout
      # Cache
      - restore_cache:
          keys:
            - deps-{{ checksum "poetry.lock" }}
      - *build_upload_to_pipy
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - testing
      - build_deploy
